import { NextRequest, NextResponse } from "next/server";
import {
  createServerSupabaseClient,
  createServiceRoleClient,
} from "@/lib/supabase/server";
import { z } from "zod";

const inputSchema = z.object({
  seller_id: z.string().uuid().nullable(),
});

/**
 * PATCH /api/admin/orders/[id]/seller
 *
 * Admin-only. Re-attributes an event order (and any tickets it generated)
 * to a different seller, or clears the attribution with seller_id=null.
 *
 * If the seller isn't assigned to the event yet (event_sellers), an entry
 * is inserted with can_sell=true so the seller appears in event reports.
 */
export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await params;
    const supabase = await createServerSupabaseClient();
    const service = createServiceRoleClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: "No autenticado" }, { status: 401 });
    }

    const { data: profile } = await supabase
      .from("profiles")
      .select("role")
      .eq("id", user.id)
      .single();
    if (!profile || profile.role !== "admin") {
      return NextResponse.json(
        { error: "Solo admins pueden cambiar el vendedor" },
        { status: 403 },
      );
    }

    const body = await request.json();
    const parsed = inputSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: "seller_id inválido" },
        { status: 400 },
      );
    }
    const newSellerId = parsed.data.seller_id;

    const { data: order } = await service
      .from("event_orders")
      .select("id, event_id")
      .eq("id", id)
      .single();
    if (!order) {
      return NextResponse.json(
        { error: "Orden no encontrada" },
        { status: 404 },
      );
    }

    // Ensure the seller is assigned to the event (so reports + seller dashboards work)
    if (newSellerId) {
      const { data: assignment } = await service
        .from("event_sellers")
        .select("id, can_sell")
        .eq("event_id", order.event_id)
        .eq("seller_id", newSellerId)
        .maybeSingle();

      if (!assignment) {
        await service.from("event_sellers").insert({
          event_id: order.event_id,
          seller_id: newSellerId,
          can_sell: true,
          can_scan: false,
        });
      }
    }

    // Update the order
    const { error: updErr } = await service
      .from("event_orders")
      .update({ seller_id: newSellerId })
      .eq("id", id);
    if (updErr) {
      console.error("Order seller update error:", updErr);
      return NextResponse.json(
        { error: "Error al actualizar la orden" },
        { status: 500 },
      );
    }

    // Propagate to all tickets generated by this order
    await service
      .from("event_tickets")
      .update({ seller_id: newSellerId })
      .eq("order_id", id);

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error("Order seller PATCH error:", err);
    return NextResponse.json(
      { error: "Error interno del servidor" },
      { status: 500 },
    );
  }
}
